---
abstract: 'Cx::C::Sugar plugins'
author:
  - 'Jan Henning Thorsen - jhthorsen -at- cpan.org'
build_requires:
  Data::Dumper: 2.1
  ExtUtils::MakeMaker: 6.42
  Moose: 0.94
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-Controller-Sugar-ActionPack
no_index:
  directory:
    - inc
    - t
requires:
  CatalystX::Controller::Sugar: 0.05
  File::Slurp: 9999.1
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=CatalystX-Controller-Sugar-ActionPack
  homepage: http://search.cpan.org/dist/CatalystX-Controller-Sugar-ActionPack
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jhthorsen/catalystx-controller-sugar-actionpack.git
version: 0.03
